changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🏗️ Infrastructure"
      labels:
        - ci
        - infra
        - deps
        - deployment
    - title: "📖 Documentation"
      labels:
        - docs
    - title: "Other Changes"
      labels:
        - "*"